#ifndef ART_FTDS_H_
#define ART_FTDS_H_

#include "art.h"
#ifndef WIN32_DEBUG
#include "common_ftds_def.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef WIN32_DEBUG
typedef enum
{
    ART_START = 550,
    ART_MG_ONEKEY,
    ART_MG_ONEKEY_PREPARE,
    //ART_MG_ONEKEY_SNAPTREE_DELTA,
    ART_MG_UPDATE_SNAP_TREE_INFO,
    ART_MG_CHECK_BUFF_MANAGER,
    ART_MG_SINGLE_SNAP_TREE,
    ART_MG_COMPLEX_SNAP_TREE,
    ART_MG_FLUSH_LAST_SNAP_PATH,
    ART_MG_PROMOTE_ANALYZE,
    ART_MG_TRY_FLUSH_BUFF,
    ART_MG_FREE_SNAP_PATH,
    ART_MG_PROMOTER,
    ART_MG_FLUSH_SNAP_PATH_NODE_CHILD,
    ART_MG_ONEKEY_SNAPTREE,
    ART_MG_ONEKEY_ADDSNAPTREE,
    ART_MG_ONEKEY_SWITCHPATH,
    ART_MG_ONEKEY_SNAPTREE_ALLOCMEM,
    ART_MG_ONEKEY_SNAPTREE_CORE,
    ART_MG_ONEKEY_SNAPTREE_FLUSH,
    ART_MG_MERGEADDTGTPATH_ARBITRATE,
    ART_MG_MERGEADDTGTPATH_ADDSNAPPATH,
    ART_GET_IN_ONE_TREE,
    ART_SEEK_IN_ONE_TREE,
    ART_BATCH_GET_KEYS,
    ART_BATCH_GET_MEM_ONE_KEY,
    ART_BATCH_GET_SS_KEYS,

    ART_CREATE_TGT_PATH_INNER,
    ART_CALLBACK_ARBITRATE,
    ART_CALLBACK_GC_RECORD,
    ART_CALLBACK_SNAP_TREE_ARBITRATE,
    ART_MG_PREPARE_FLUSH_PATH_CHILD,
    ART_MG_TRY_TO_FLUSH_BUFF,
    ART_MG_PREPARE_FLUSH_SNAP_CHILD,
    ART_ITOR_ST_NEXT_CONDITION,
} FtdsCommType;
#endif

#ifdef ARTREE_DEBUG
void start_comm_ftds(uint32_t point, uint64_t *ftds_timeStart);

void end_comm_ftds(uint32_t point, uint32_t status, uint64_t ftds_timeStart);
#endif

#ifdef __cplusplus
}
#endif
#endif

